### ISSUE TITLE
Lidwake

### ISSUE THREAD

**Issue by tlefko** [tlefko/macOS-Mojave-XPS13-9350#1]
On the current release, I haven't found a way to patch @syscl 's Lidwake kext. The KEXT cannot be loaded in Mojave and therefore lid wake doesn't work properly.

Help Appreciated.

**Comment by syscl** [comment]
I am still waiting for the final release of Mojave and using 10.13.6 atm.

**Comment by tlefko** [comment]
@syscl Gotcha, have you had a chance to test this beta or just waiting to try until after.

**Comment by syscl** [comment]
Would you mind uploading the following kext to me such that I can give the assemble a close to look to see if I have to update my patch in EnableLidwake.kext. Here's the kext I want to check:
```
AppleIntelFramebufferAzul.kext
AppleIntelKBLGraphicsFramebuffer.kext
AppleIntelSKLGraphicsFramebuffer.kext
``` 
Thank you.

**Comment by tlefko** [comment]
Gotcha, I just updated them to project files. Any clue why restarting doesn't work? (Black screen, no shutdown)

**Comment by tlefko** [comment]
@syscl I'm new to Github, how can I delete the files once you view them?

**Comment by syscl** [comment]
no need to upload any files because it seems like 10.14 the Framebuffer files have been changed quiet a lot.

**Comment by syscl** [comment]
Cannot restart? Should be ACPI issue.

**Comment by tlefko** [comment]
Gotcha, is there's some other more direct way to communicate? This is kind of difficult. 

To expand on your last point; I don't have the skillset or knowledge to help with ACPI issues. Using your Clover folder simply crashed the installer, so I compiled a stock clover one and booted with that, then attempted to implement your patches. 

I'll explain further what broke in a more direct line if it's possible, thanks.

**Comment by tlefko** [comment]
@syscl as well as what was changed from your Kexts, deploy to make it compatible

**Comment by tlefko** [comment]
@syscl any word on it?

**Comment by syscl** [comment]
Currently working on it.

**Comment by syscl** [comment]
Please try the latest EnableLidwake v4.0.1 to see if this fix the Mojave issue. I use a more general get platform id symbol.

**Comment by tlefko** [comment]
worked!
