### ISSUE TITLE
Copying files

### ISSUE THREAD

**Issue by thatcobbyguy** [tlefko/macOS-Mojave-XPS13-9350#3]
Hello, could you clarify what you mean when it says "Copy contents of the repository to EFI folder (No EFI in boot)"?

Should I copy just the Clover folder or just drag all the files into the EFI partition?
And what do you mean by "No boot folder in EFI"?

Thank you!

**Comment by tlefko** [comment]
Hi @mcobb98 , copy all the files from the Files zip direct to the EFI Partition. Ignore the Boot folder line, just copy everything over and let me know if it works out for you.

**Comment by thatcobbyguy** [comment]
I keep getting an ACPI error saying “namespace lookup failure” and AE_NOT_FOUND. Any ideas?

**Comment by tlefko** [comment]
Hi @mcobb98. Do you have the same model? Try deleting the ACPI files and booting again. also make sure your bios is correct and all the files copied successful

**Comment by tlefko** [comment]
This is when booting the installer right?

**Comment by thatcobbyguy** [comment]
My specs are:
i7-6560U @2.2GHz
Iris 540
3200x1800

I deleted the ACPI from origin and patched, and when I boot from installer in verbose it stops and displays the prohibitory sign.

SATA is AHCI
Secure or disabled
Fast boot set to minimal

Strange, do you think it has something to do with my bios version being 1.7?

**Comment by thatcobbyguy** [comment]
Adding usbinjectall.kext from Tonymacx86 solved the issue!

**Comment by tlefko** [comment]
@mcobb98 Really? That's surprising. Feel free to let me know about anything else. I'm curious if Iris graphics work. Also, I'd recommend removing my APCI patches.. They might cause as our specs are different

**Comment by tlefko** [comment]
(Just repatch with deploy)

**Comment by tlefko** [comment]
Really? That's surprising. Feel free to let me know about anything else. I'm curious if Iris graphics work. So to be clear, you deleted APCI and then added USBinject and it booted? That's probably because the USB patches are done with XHCI. Anyway, glad you got it working. Just make sure you delete overlapping USB Patches and rematch ACPI later

**Comment by tlefko** [comment]
@mcobb98

**Comment by thatcobbyguy** [comment]
I had already deleted files from the ACPI folder when I tried to boot from the installer originally. I only know the (very) basics of hackintoshing so far so I just found a thread on tonymac that had the same error screen as me and copied his solution

**Comment by tlefko** [comment]
@mcobb98 gotcha, so after you did this you were able to install the OS?

**Comment by thatcobbyguy** [comment]
@tlefko I was able to install mojave, yes! I've yet to run the depoy script though. I've had a lot of assignments over the past few days so I've been using windows to get them all done. Will update after I run the script.

With Syscl's deploy in High Sierra I needed to rename the SSDT tables, is that necessary with your modified deploy?

**Comment by tlefko** [comment]
Personally I don't even think my config even uses them. However, you can make that call for yourself. I'm not great with that kind of stuff. After you run deploy, make sure you do however install the manual patches. Let me know if it works out for you. @mcobb98 

I know that SSD power management doesn't work and the battery life/thermal isn't amazing

**Comment by tlefko** [comment]
@mc

**Comment by tlefko** [comment]
Yeah I get it absolutely, I'm a student myself and just couldn't afford to get a mac so I understand the need to have something to get things done. I currently dual boot in both OSX and windows.

**Comment by tlefko** [comment]
@mcobb98 Could you explain how to add SSDT patches to clover config?
