### ISSUE TITLE
Old Files

### ISSUE THREAD

**Issue by tlefko** [tlefko/macOS-Mojave-XPS13-9350#4]
Replace your old EFI folder with the one linked in the description 

There was a mistake in the previous upload not intended for Mojave yet.

The System can't boot with the old version

**Comment by tlefko** [comment]
@mcobb98

**Comment by thatcobbyguy** [comment]
I attempted to install Mojave yesterday (with the old files, I guess) and every time I tried to format the drive with disk utility the installer would reboot). Have you tried installing Mojave release yet?

**Comment by tlefko** [comment]
I knew that would happen.

I uploaded the wrong thing those were for Sierra

Please try with the new files and get back to me. Yes I was running Mojave already when I uploaded the old files but they were from my old Sierra dell

**Comment by tlefko** [comment]
@mcobb98 I copied the wrong contents over esentially which caused the issue. I was using different things than I uploaded. I uploaded an even newer version now but either should work adamantly.

**Comment by thatcobbyguy** [comment]
I'll try to install this weekend! I still have a lot of schoolwork to finish and don't want anything to go wrong with my files

**Comment by thatcobbyguy** [comment]
@tlefko a note, there are now no files uploaded to the repository

**Comment by tlefko** [comment]
@mcobb98 I think they're under the same name

Check for a file called Files-2 2.zip

**Comment by tlefko** [comment]
on my end it's here

**Comment by tlefko** [comment]
If you see it, use that instead of the previous. On mine it's still here

**Comment by thatcobbyguy** [comment]
Only the readme and voodoohda are available

**Comment by tlefko** [comment]
Take a look now? Look for files-2 3.zip @mcobb98

**Comment by thatcobbyguy** [comment]
perfect!

**Comment by tlefko** [comment]
@mcobb98 Any luck?

**Comment by thatcobbyguy** [comment]
@tlefko Had a super busy weekend, sorry. I went to install Mojave with your files and say syscl added some Mojave commits so I installed with his. So far everything works except audio (I had to use voodoohda), restarts, and my screen glitches after waking from sleep. 

How’s it working on yours?

**Comment by tlefko** [comment]
@mcobb98 Hey, thanks for getting back to me. Being honest I have actually zero bugs. Except for I haven't updated lidwaje with his commit yet. Swap your EFI files with mine and try it off a usb or something. Or for best results, back his to a usb and try mine. Let me know results, thanks

**Comment by tlefko** [comment]
Note in my build there is voodoohda. But no glitches for screen or USBs. Restarts still a no though

**Comment by tlefko** [comment]
If your using the usb u may need to manually add the boot EFI path in the file. Testing my current config uploaded which I just did it booted perfectly off a usb after manually setting boot path
