### ISSUE TITLE
hello 10.14 install  screen dark

### ISSUE THREAD

**Issue by yuzhenghuan** [tlefko/macOS-Mojave-XPS13-9350#5]
Thr 3k screen gets dark when 2 min remains，i5-6200,acpi has been deleted.I don't touch the mouse and keyboard.

**Comment by tlefko** [comment]
@yuzhenghuan Hi, can you fill in your full computer specs and info?

- also is this during the installer? thanks.

**Comment by tlefko** [comment]
is it during the installer where the computer has already restarted once and is booting off the hard drive?

**Comment by tlefko** [comment]
It's possible the install competed and attempted restart. -- because restarting is broken you may just need to turn it on again and Mac will be installed

**Comment by yuzhenghuan** [comment]
No, I wait for 20min,then i reboot it manually,select 10.14 partition,my screen gose dark again, no reaction,i can not get the error report.Even i try to update the clover.No change.I quit.I have install ed 10.12.6 using @syscl.I just want to try to experience  mojave so that I install mojave in a mobile HDD.I guess it's  the question.I appreciate your reply.I'm a chinese student.My english is not good.I hope you can understand  what i want to express.Thanks again.
On 09/29/2018 12:51, tlefko<mailto:notifications@github.com> wrote:

It's possible the install competed and attempted restart. -- because restarting is broken you may just need to turn it on again and Mac will be installed

**Comment by tlefko** [comment]
@yuzhenghuan. You need to erase @syscls EFI files and replace them with mine. Using his will break the install. 

You can't install it on a mobile HDD because the drivers are designed to work with a PCIe SSD.

If you have the 6200u and Intel HD 520. You can put back the acpi files.

You can make another partition on your internal hard drive to try Mojave, or erase Sierra (highly recommend) 

To get error messages, when the computer turns on hold f12, wait for my clover boot options to come up and press any key to get the clover menu. Then add the boot flag -v.

Before you try to get boot error messages, try my other idea of putting it on internal ssd

**Comment by tlefko** [comment]
@yuzhenghuan I remember your issue happening with me when I used his EFI files. Or when I tried to not do fresh install.

Also make sure to use the latest files from yesterday

**Comment by yuzhenghuan** [comment]
ok i'll try to use internal ssd.I just don't want to erase my 10.12 because there's too much valuable files.I 'll figure it out.Thanks for your help.


On 09/30/2018 01:02, tlefko<mailto:notifications@github.com> wrote:

@yuzhenghuan<https://github.com/yuzhenghuan> I remember your issue happening with me when I used his EFI files. Or when I tried to not do fresh install.

Also make sure to use the latest files from yesterday

**Comment by tlefko** [comment]
@yuzhenghuan Gotcha, just make sure you use the right EFI when booting. Let me know the results.

**Comment by yuzhenghuan** [comment]
No problem.I'll reply once I success.Thanks.


On 09/30/2018 15:11，tlefko<notifications@github.com><mailto:notifications@github.com> wrote：

@yenghenghuan Gotcha, just make sure you use the right EFI when booting. Let me know the results.

**Comment by yuzhenghuan** [comment]
10.14 is not perfect,but i don,t have 10.13.6 EFI,you have 10.13 clover?

On 09/30/2018 15:11, tlefko<mailto:notifications@github.com> wrote:

@yenghenghuan Gotcha, just make sure you use the right EFI when booting. Let me know the results.

**Comment by tlefko** [comment]
Just use the EFI included on the repo @yuzhenghuan just copy the whole repository to your EFI folder of your pc

**Comment by tlefko** [comment]
@yuzhenghuan did it end up working?

**Comment by yuzhenghuan** [comment]
no i don,t try again,I share your efi to my friend,he will try!I will feed back once he successes


On 10/03/2018 04:35, tlefko<mailto:notifications@github.com> wrote:

@yuzhenghuan<https://github.com/yuzhenghuan> did it end up working?

**Comment by tlefko** [comment]
@yuzhenghuan Alright sounds good!
