### ISSUE TITLE
Wifi Swap

### ISSUE THREAD

**Issue by EchoTroop** [tlefko/macOS-Mojave-XPS13-9350#7]
Because of the "FAKEPCIID and FAKEPCIID_Broadcomm" kext files, the default wifi card that comes with the XPS 9350 does not need to be switched out?
If not, are there any noticeable performance changes?

**Comment by tlefko** [comment]
Hi, which default wireless card is in the 9350 again? If it's the 1820A then as far as I know it should be ok! @EchoTroop
