### ISSUE TITLE
hello 10.14 install screen dark

### ISSUE THREAD

**Issue by heimeii** [tlefko/macOS-Mojave-XPS13-9350#8]
the same as 
https://github.com/tlefko/macOS-Mojave-XPS13-9350/issues/5
![image](https://user-images.githubusercontent.com/18004891/52797606-29ca9e00-30b1-11e9-8379-f7d7430ef59a.png)
i need some help, thanks

**Comment by tlefko** [comment]
Hi, please send updated pics
