### ISSUE TITLE
Questions please

### ISSUE THREAD

**Issue by x4080** [tlefko/macOS-Mojave-XPS13-9350#9]
The file to copy to boot disk in efi, is the content of the zip right?

And you said no boot folder? But inside zip files there is boot folder

Im sorry for troubling you

And still work for 14.4 right?

Thanks

**Comment by x4080** [comment]
Never mind, already asked before

But in booting with usb installer mojave 14.4, it stucks at 50% should just wait?

**Comment by x4080** [comment]
Ok now it goes to black screen, is it because of different vga card? Im using the i7 3k screen version if i remember correctly

**Comment by x4080** [comment]
After replacing acpi, it progress to install screen but now the problem is keyboard and mouse is not detected

Should we use external keyboard and mouse?

**Comment by tlefko** [comment]
Alrighty, let's discuss

so, what is the model of your computer Dell xps 13 9350 i7?

--- Try to use external keyboard and mouse, I would suggest updating the voodoo keyboard drivers and mouse to fix that issue (voodoops2) if it doesnt wokr during installer yes try external and mouse

**Comment by x4080** [comment]
Hi @tlefko,

My model is the one with 3k screen with 128gb SSD (Samsung), already make it Sierra with help of syscl, and for a long time never update it, then I need the Xcode to develop and seems it cannot install Xcode 10, 

And now, I installed Mac OS High Sierra, and the strange thing is I'm using your Clover ! Thanks for your clover I can boot the High Sierra install disk (was using syscl's but cannot boot), and the long boot process etc is happening because of I'm still using the built in wifi card DW1820A if not mistaken - the solution is to disable it in BIOS (thanks to a guy in the syscl github)

Now already had the high Sierra running, and thanks for replying back, should I just upgrade it to Mojave ? Or try to do the USB installation again ?

Thanks again for your clover man, already 3 days and cannot install Mojave and then High Sierra

**Comment by tlefko** [comment]
Yeah try for the upgrade, I did mine by upgrading Sierra to Mojave so yours
should work too. I'm using the DW1820A too. I'm glad yours improved

**Comment by x4080** [comment]
Did you disable the 1820a? When I'm not disabling it, the installer is not booting, and you can use 1820a to connect to network ? You have the driver ?

Thanks to your hard work I can at least update to high sierra :)

BTW what trackpad driver do you use ? Currently I dont have any gesture available, should I use Voodoops2Controller? I think syscl recommend AppleTouchpad or something when using latest mac os but its limited

**Comment by tlefko** [comment]
I didn't disable 1820a, I would recommend aby voodoo driver should suffice

**Comment by tlefko** [comment]
@x4080 has Mojave worked?

**Comment by x4080** [comment]
Havent tried it yet (scared hehe), already installing xcode and working well, I use VoodooI2C and works great, if you like to use it, I use the files from https://github.com/hackintosh-stuff/XPS9350-macOS

To prepare for Mojave, what version of Clover do you use ? So I just update clover, use your clover folder in the boot disk, boot installer and select the current partition ? Or using the mac os upgrade process is enough ?

**Comment by tlefko** [comment]
@x4080 backup clover, I use an older version as I haven't changed my setup since December. Install the update normally, boot the clover off a usb if it gets wiped, and see if it works

**Comment by x4080** [comment]
Thanks @tlefko , I tried building mojave boot disk again (10.14.4), using your clover for boot, and still no go, cannot get into the installer, then I delete the acpi/patched folder and still no go 

Are you using 10.14.4 ? Or this version is difficult to boot

**Comment by tlefko** [comment]
currently on 14.2, started at the very beta. I can send u my exact current
folder if u want

**Comment by tlefko** [comment]
(of clover)

**Comment by x4080** [comment]
@tlefko Sure thanks,  should I use it with 14.2 ? Can we download the 14.2 still ? Or it will work with 14.4 ?

**Comment by tlefko** [comment]
don't think it should matter.... where should I send my clover too?

**Comment by x4080** [comment]
You can send it to my email address x4080@yahoo.com

Thanks, sorry for late reply, busy using the Xcode hehe

**Comment by tlefko** [comment]
Hi, do you still need it?

**Comment by x4080** [comment]
Sure I'll try it

**Comment by Wes-White** [comment]
Can you send it to me as well? 

wesleyrwhite86@gmail.com

**Comment by tlefko** [comment]
@Wes-White EFI folder?

**Comment by Wes-White** [comment]
@tlefko Yes please I'm having a hard time booting after I complete the install. The loading bar will fill half way sometimes all the way but it never loads the OS

**Comment by tlefko** [comment]
boot verbose and send pic, and ur specs

**Comment by Wes-White** [comment]
I reinstalled Pop since I couldn't boot after the Mojave install and needed to get some work done. I tried to recreate a USB today with the same instructions but couldn't even get to the installation process this time.It would either keep restarting or leave a message waiting for system restart and do nothing. 

Specs are: 
i7-6500 
Skylake 520
1.9.0 Bios

**Comment by tlefko** [comment]
Follow all steps besides USB, send your email and I'll send you my EFI to
put onto your drive

**Comment by Wes-White** [comment]
@tlefko  wesleyrwhite86@gmail.com 

Thank you so much
